### ISSUE TITLE
Console error when attempting to use 

### ISSUE THREAD

**Issue by nightpool** [r12a/app-analysestring#3]
<img width="1622" alt="image" src="https://github.com/r12a/app-analysestring/assets/233815/37fff9ac-ee32-436e-a7e3-b5a7de58823f">

```
Uncaught ReferenceError: scriptGroups is not defined
    at functions.js:72:12
functions.js:944 Uncaught ReferenceError: sNotAChar is not defined
    at getCharType (functions.js:944:45)
    at getDataFor (functions.js:953:17)
    at listChars (script.js:68:13)
    at makeList (script.js:45:16)
    at HTMLInputElement.onchange (index.html:27:251)
3functions.js:944 Uncaught ReferenceError: sNotAChar is not defined
    at getCharType (functions.js:944:45)
    at getDataFor (functions.js:953:17)
    at listChars (script.js:68:13)
    at makeList (script.js:45:16)
    at HTMLButtonElement.onclick (index.html:36:65)
```

**Comment by r12a** [comment]
I think this is now fixed. Thanks for raising the issue.
